# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'PokemonTCG_MVVM' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for PokemonTCG_MVVM
	pod  'RxSwift' ,  '6.1.0' 
  pod  'RxCocoa' ,  '6.1.0'
  pod 'SDWebImage', '~> 5.0'
  pod 'ImageViewer', :git => 'https://github.com/tovkal/ImageViewer'
end
